export const users = [
  {
    firstName: "Admin",
    lastName: "Admin",
    username: "admin1",
    email: "admin1@gmail.com",
    phoneNumber: "+917977504431",
    password: "admin1",
    accountNumber: "NA",
    balance: 0,
  },
  {
    firstName: "Admin",
    lastName: "Admin",
    username: "admin2",
    email: "admin2@gmail.com",
    phoneNumber: "+917977504432",
    password: "admin2",
    accountNumber: "NA",
    balance: 0,
  },
  {
    firstName: "Admin",
    lastName: "Admin",
    username: "admin3",
    email: "admin3@gmail.com",
    phoneNumber: "+917977504433",
    password: "admin3",
    accountNumber: "NA",
    balance: 0,
  },
];
